[package]
name = "racc_test"
version = "0.1.0"
authors = ["Arlie Davis <arlie.davis@gmail.com>"]
edition = "2018"

[dependencies]
racc = { path = "../racc" }
racc_runtime = { path = "../racc_runtime" }
log = "0.4.*"
